### ISSUE TITLE
Generated CSS wrong name

### ISSUE THREAD

**Issue by danieldisu** [axitkhurana/buster#11]
When I run buster generate, it create all the needed files, but the "screen.css" gets saved as screen.css?v=e1a4208fa8 and everytime I run `buster generate`I must change the name of that css file.

**Comment by axitkhurana** [comment]
Hey @danieldisu,

Thanks for reporting. Please provide the Ghost version number and the OS you are running. And if you're running a different theme other than the default. Will help me replicate the issue and fix.

**Comment by Phonbopit** [comment]
I had a same problem on Ghost 0.4

after run `buster generate` when I look at /static/index.html stylesheet link to correct screen.css?v=aaaa

but when I run `buster preview`  and `view-source:http://localhost:2368/` screen.css?v=bbb is changed.
- OS : Ubuntu 13.10
- Ghost 0.4, Casper theme.
- pip v.1.4.1, python 2.7.5

p.s. I download and test on Ghost 0.3.3 it work fine

**Comment by ghost** [comment]
Firstly, thank you for Buster. It is awesome.

I too am experiencing this issue. Running Ghost 0.4 with a slightly modified Casper theme. Something adds a randomly string to the end of .css and .js files which breaks the static sites.

**Comment by axitkhurana** [comment]
Thanks @jackpea. I'll try to fix it over the weekend, seems to be an issue with the new 0.4 version.

**Comment by lianghanzhen** [comment]
Hi @axitkhurana,  I have fixed this issue and send you a pull request.

**Comment by jaredly** [comment]
fixed by #13

**Comment by axitkhurana** [comment]
Thanks to @lianghanzhen, this has been fixed. Please update buster using `pip install --upgrade buster` and let me know if you are facing any issues.

**Comment by jaredly** [comment]
thank you!! buster is such a useful tool
