### ISSUE TITLE
Error on running generate command (windows x64)

### ISSUE THREAD

**Issue by drowsyrobotboy** [axitkhurana/buster#15]
Hey! I get this error on running "buster generate --domain=http://127.0.0.1:2368".

I've installed all dependencies.. hopefully. please help me out.

![buster](https://f.cloud.github.com/assets/3001063/1961797/fa544d5e-827a-11e3-84f7-b8ba35636551.jpg)

Thank you.

**Comment by axitkhurana** [comment]
Whoops, sorry about that, the code uses \ characters to split the wget command on separate lines for readability. Never thought I'll use it on Windows. Let me push a fix and get back.

**Comment by drowsyrobotboy** [comment]
Lovely. Thank you :smile:

**Comment by mii9000** [comment]
@maruthip25  #23 Will fix all windows related problems and then do some more.

**Comment by axitkhurana** [comment]
Just removed \ s, should work now, let me know if it fails!
