### ISSUE TITLE
"index.html" is being appended to all directory links

### ISSUE THREAD

**Issue by shaunlebron** [axitkhurana/buster#16]
This is a cosmetic URL problem, a side effect of #5. (problem discussed on [super user](http://superuser.com/questions/275492/wget-convert-links-appending-index-html))

We can either:
1. build a custom version of wget that chops off "index.html" from the [converted-url here](https://github.com/jay/wget/blob/master/src/convert.c#L304))
2. modify buster.py to correct the links in HTML files after generating.
3. inject extra javascript into the "assets/js/index.js" to correct the links on client side.

**Comment by axitkhurana** [comment]
Hey Shaun,

Thanks for reporting this. I feel the best way would be to modify `buster.py` to correct links in HTML files after generation. This would be a part of the generate command.

Maintaining a fork of `wget` will not be an easy task and would add more complexity to the buster installation. I won't be able to find time to work on this until next week. Feel free to send a pull request if you would like to.

**Comment by shaunlebron** [comment]
A simple text-based replacement could potentially modify more than intended (e.g. code examples in blog content).  So, we should probably use PyQuery to safely parse/search/modify an html tree.  

``` python
from pyquery import PyQuery
abs_url_regex = re.compile(r'^(?:[a-z]+:)?//', flags=re.IGNORECASE)
def fixLinks(text):
    d = PyQuery(text, parser='html')
    for element in d('a'):
        e = PyQuery(element)
        href = e.attr('href')
        if not abs_url_regex.search(href):
            new_href = re.sub(r'/index\.html$', '/', href)
            e.attr('href', new_href)
    return d.__unicode__().encode('utf8')
```

---

### alternative

Adding the following code to `assets/js/index.js` would do the same thing:

``` javascript
/* Buster: correct local directory links to not include "index.html" */
(function($){
    var absUrlPattern = new RegExp('^(?:[a-z]+:)?//', 'i');
    $(document).ready(function(){
        $('a').each(function(){
            var e = $(this);
            var href = e.attr('href');
            if (!absUrlPattern.test(href)) {
                var new_href = href.replace(/\/index\.html$/, '/');
                e.attr('href', new_href);
            }
        });
    });
}(jQuery));
```

**Comment by martgnz** [comment]
Any news on this? How can I apply the solutions?

**Comment by shaunlebron** [comment]
Solution found in pull request on #20

**Comment by fluke** [comment]
@axitkhurana Is this going to be implemented into buster? I had a look at your blog and the links are fine. So is it just a matter of not updating your latest changes?
