### ISSUE TITLE
Static pages support broken?

### ISSUE THREAD

**Issue by martgnz** [axitkhurana/buster#18]
I know that buster doesn't support static pages. I did the trick mentioned in https://github.com/axitkhurana/buster/issues/7 and it generates the page, but without the index.html string. When I try to open the page in the browser it doesn't work.

**Comment by axitkhurana** [comment]
Can you please give me more details on how to reproduce this? I'm not sure what you mean by 'without the index.html string'.

The following details should help me debug this:
- Path of the static page in Ghost
- link added in the template as suggested in #7 
- the generated page name and path (you can get that by browsing static directory)
- the URL when the browser tries to open the page

**Comment by martgnz** [comment]
Now I switched my page to a simple post, just for commodity. I'll look at this asap.

**Comment by martgnz** [comment]
I solved this creating a static page as a normal post, generating the blog and then changing the post to a static page and generating again

**Comment by axitkhurana** [comment]
I believe all linked static pages will be generated. Please reopen this issue if that is not the case.

**Comment by WillemWijnans** [comment]
I was having the same problem with my about-me static page. I have now renamed the about file (with no extension) to about.html but the page rendered incorrectly. I had to change the post-holder height (comment out the 100%) now it works with static pages.

**Comment by tomvo** [comment]
for me the static pages are also generated without extension, meaning the browser will try to download it. Manually renaming works but it would be great if the .html was added automatically.

**Comment by miccferr** [comment]
+1 same problem as @tomvo and @WillemWijnans .
I sort of "automated" the procedure by adding an npm task:
`"rename": "mv static/about static/about.html"` 
so I can run multiple npm tasks with `&&` to wrap buster tasks (i.e. generate and deploy) in one npm command.

**Comment by miccferr** [comment]
Although @apandichi fix solved the issue once and for all.
See d9cdde755b39a74c3ea99cd8bffbbd7be94b24cd
