### ISSUE TITLE
Author pointing to nowhere

### ISSUE THREAD

**Issue by martgnz** [axitkhurana/buster#19]
When I enter my website in the local copy of Ghost it runs fine, but at the time of deploying it it points to localhost, then the article, then the website.

Something like this: http://127.0.0.1:2368/ARTICLE/WEBSITE.

How can I fix this?

**Comment by axitkhurana** [comment]
I assuming the website is in form `axitkhurana.com`. Try specifying `http://` or `https://` before the site URL e.g. `http://axitkhurana.com`. Does that help?

**Comment by martgnz** [comment]
Awesome, fixed using http:// before the site.
Thanks for your help!
