### ISSUE TITLE
meta tag - canonical link 'index.html'

### ISSUE THREAD

**Issue by chakming** [axitkhurana/buster#21]
all page generate with canonical link 'index.html', and not the exact full link.

**Comment by martgnz** [comment]
Read this: https://github.com/axitkhurana/buster/pull/20

**Comment by shime** [comment]
here's a dirty hack I'm using for now - run it from the root of your ghost blog

```
find static/ -type f -name *.html -exec sed -i 's/index\.html//g' {} +
```

or place this somewhere in generate task

```
os.system("find %s -type f -name *.html -exec sed -i 's/index\.html//g' {} +" % static_path)
```

**Comment by martgnz** [comment]
@shime it throws this error for me: `sed: 1: "static//akademy-es-2014 ...": bad flag in substitute command: 'm'`

**Comment by martgnz** [comment]
Solved with [this](https://stackoverflow.com/questions/17534840/sed-throws-bad-flag-in-substitute-command). Awesome!

**Comment by shime** [comment]
@mgonzalezgmz :beers:

sometimes OSX and GNU tools are incompatible, glad you sorted that one out! :)

**Comment by martgnz** [comment]
@shime yes, I definitely owe you some :beers: for this fix. The index.html string was super annoying for me :+1:

**Comment by fluke** [comment]
@shime Are there any possible issues arising from this command?

**Comment by shime** [comment]
@kartikluke maybe and it depends. This just removes all occurences of _index.html_.

**Comment by axitkhurana** [comment]
Just updated. Should be removed now. Upgrade using `pip install --upgrade buster`
