### ISSUE TITLE
buster setup

### ISSUE THREAD

**Issue by ghost** [axitkhurana/buster#22]
When I try to setup buster, I receive always the same message:
![1](https://cloud.githubusercontent.com/assets/2954061/3005705/8987d3aa-ddee-11e3-97b3-0f3035336c14.png)
![2](https://cloud.githubusercontent.com/assets/2954061/3005706/8989de2a-ddee-11e3-93b0-4208cdfa9597.png)

I have tried in Windows 7 and in Ubuntu 14.04

**Comment by martgnz** [comment]
Install Git, this solved the issue for me.

**Comment by axitkhurana** [comment]
Thanks @mgonzalezgmz . Yes, as mentioned in the README Git is a requirement.

`sudo apt-get install git` for Ubuntu

Please reopen this if the issue persists.

EDIT: Just realized README doesn't mention Git explicitly, also pointed out it #10
