### ISSUE TITLE
Create an RSS feed

### ISSUE THREAD

**Issue by sdaityari** [axitkhurana/buster#25]
/feed doesn't give me the RSS feed. I think this would be a welcome change!

Or does it already exist?

**Comment by martgnz** [comment]
Don't worry, your feed lives in /rss. But I don't know if buster generates RSS for tags..

**Comment by axitkhurana** [comment]
Ghost should do the generation part and buster would crawl and save the rss file at /rss e.g.: http://blog.axitkhurana.com/rss/ . Should work fine with the tags too.

Thanks @mgonzalezgmz :)

@sdaityari Is it expected to be at /feed? Please reopen with details if such is the case.
