### ISSUE TITLE
Cannot pip install buster on Windows

### ISSUE THREAD

**Issue by mii9000** [axitkhurana/buster#28]
I am left with this error on my Windows 8.1 machine:

```
Command python setup.py egg_info failed with error code 1 in C:\Users\Ibrahim\AppData\Local\Temp\pip_build_Ibrahim\async
```

When I run `pip install buster`

**Comment by mii9000** [comment]
Was PC related or python version related error.

**Comment by aemxn** [comment]
Same here. What python version are you using @Ibrahim-Islam?
