### ISSUE TITLE
@v tag added to all stylesheets and js files

### ISSUE THREAD

**Issue by avinoth** [axitkhurana/buster#33]
when I do the generate the css files and js files get automatically appended with @v tag followed by some random strings... This works fine in local browser but the same is not while using in Github pages... here is the link avinoth.github.io - In the first page's css I have removed the "@v tag" but go to other pages or the individual post page itself.....

**Comment by suksit** [comment]
This happened to me on Windows as wget escaped `?` in query string with `@`.

To prevent this, I had to add `--restrict-file-name=unix` to wget command line options.

``` python
        command = ("wget \\"
                   "--recursive \\"             # follow links to download entire site
                   "--convert-links \\"         # make links relative
                   "--page-requisites \\"       # grab everything: css / inlined images
                   "--no-parent \\"             # don't go to parent level
                   "--directory-prefix {1} \\"  # download contents to static/ folder
                   "--no-host-directories \\"   # don't create domain named folder
                   "--restrict-file-name=unix \\"   # don't escape query string
                   "{0}").format(arguments['--domain'], static_path)
```

**Comment by pratjz** [comment]
hi is this solved ? am getting same issue
