### ISSUE TITLE
No RSS for tags

### ISSUE THREAD

**Issue by luizfaias** [axitkhurana/buster#36]
Before complaining about anything, let me just say that Buster is a great tool :smile:

Are there any plans for supporting RSS on tags?

I'm using Ghost 0.5.2.

Example (404 error):
http://luizfaias.com/tag/matrix/rss

Thanks,
Luiz

**Comment by axitkhurana** [comment]
Thanks @luizfaias !

I haven't been able to work on buster for quite some time. If you look at the buster script, you'll see it uses wget to generate static pages. As there is no link to RSS feeds of tags in the blogs wget has no idea that such pages exist and that it needs to generate those pages.

Can't promise timeline on this, but feel free to submit a pull request that adds this functionality.

**Comment by axitkhurana** [comment]
Just pushed a new release @luizfaias . Upgrade using `pip install --upgrade buster`. Should work now!
