### ISSUE TITLE
Strange Characters

### ISSUE THREAD

**Issue by pablo-grande** [axitkhurana/buster#39]
Hi, I did not saw this issue on this repository so here it goes:

I'm having some troubles on my ghost blog with characters like accents and 'ñ' (my language has those).
On my local blog I see the post just fine, but when I generate my blog on buster those characters disappear.
For example:
_Tecnología_ (means Technology) has this character "í", but on my remote blog the word is: _TecnologÃ­a_

I also did some research on the history of the code, because I don't remember this problem happening before (I used buster a few months ago) and I found that at commit d1b3d5f3543793a24f0322d9089b82d7a60a45b6 works fine, after that (at 02e9e489d3ce63c79dc9a1c2976f4cc276b32786) the strange characters appear.

Any thoughts?

**Comment by anandubajith** [comment]
is the charset UTF-8?

**Comment by pablo-grande** [comment]
Yes, it is.

Here are some photos. This is my local deployment of the ghost blog:
![local](https://cloud.githubusercontent.com/assets/5110926/5150679/12fa5a98-71d5-11e4-9f6b-8b87b7f8d62c.png)

And this is what happens when you run `buster deploy` on the blog:
![preview](https://cloud.githubusercontent.com/assets/5110926/5150697/3226dbd0-71d5-11e4-98c2-0da9331a6638.png)

As you can see the charset is correct. The second image is what becomes uploaded by the `buster deploy` command. I think the problem is at the "conversion" of the blog.

**Comment by anandubajith** [comment]
no <!doctype html> in the buster deployed blog

**Comment by pablo-grande** [comment]
I added it manually and nothing changes. I still believe that the problem is on the translation because the content of the tags is wrong, not just the view.
