### ISSUE TITLE
RSS link broken

### ISSUE THREAD

**Issue by kaicataldo** [axitkhurana/buster#44]
I just discovered Buster, and think it's amazing. I'm very eager to use this as blogging platform. I'm noticing that the RSS subscription link works on my local installation, but gives me a 404 on the live static version. Example: https://kaicataldo.github.io/

**Comment by axitkhurana** [comment]
Thank Kai. It's working on my installation: http://blog.axitkhurana.com/

Two questions:
- Does it work with buster preview?
- What version of buster are you using?

**Comment by kaicataldo** [comment]
A friend of mine also installed and is running into the same issue I'm having. 
- It only works if I leave the url in config.js as the local 127.0.0.1:2368. I've tried it with both the production and development environments.
- I'm using v0.1.3

Not sure if this is relevant, but my subscription link seems to point to /rss/ while yours points to /rss/index.rss

**Comment by arranf** [comment]
​I had the same issue on my blog and fixed it by changing the theme to
point to /rss/index.rss.​

On 8 December 2014 at 04:36, Kai Cataldo notifications@github.com wrote:

> I see that it's working. A friend of mine also installed and is running
> into the same issue I'm having.
> - It only works if I leave the url in config.js as the local
>   127.0.0.1:2368. I've tried it with both the production and development
>   environments.
> - I'm using v0.1.3
> 
> Not sure if this is relevant, but my subscription link seems to point to
> /rss/ while yours points to /rss/index.rss
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/axitkhurana/buster/issues/44#issuecomment-65975220.

## 

_​​Arran France_
​​
Communications, Youth Work, and Administration
​
_​T._ 07425 159471​

​
_​Hope Church Corby_
Registered
​ UK​
 Charity
​ ​
251549​
_​_
The Hope Centre
8 Princewood Road
Corby
NN17
​4
AP

**Comment by kaicataldo** [comment]
Cool - will give it a shot. Would be neat to see an implementation of this by the script, but it's not a big deal if it can be fixed manually.
