### ISSUE TITLE
How to generate continuously after first 'buster generate'?

### ISSUE THREAD

**Issue by devanp92** [axitkhurana/buster#46]
I want to use Buster to publish to Github Pages but after the first 'buster generate', how can I use buster to add another post to /static/ without having to manually create a directory, index.html, and replace my markdown with HTML?

**Comment by axitkhurana** [comment]
Um, use ghost on your machine as you would. After making changes in markdown, see the preview at the localhost:2368 (or similar) page. Run `buster generate` again to update HTML. `buster deploy` to deploy to Github Pages.

So, basically `buster generate` after every markdown change should generate fresh HTML pages.
