### ISSUE TITLE
Does this work on Macs? 

### ISSUE THREAD

**Issue by ghost** [axitkhurana/buster#47]
Whenever I try to install it on my mac, I get the error:

```
Command /usr/local/opt/python/bin/python2.7 -c "import setuptools, tokenize;__file__='/private/tmp/pip_build_root/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-jewwwE-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /private/tmp/pip_build_root/lxml
Storing debug log for failure in /Users/blank/.pip/pip.log
```

**Comment by axitkhurana** [comment]
Does work on a Mac. Can you look at the debug log?
`Storing debug log for failure in /Users/blank/.pip/pip.log`

**Comment by IdrissDimson** [comment]
How do you use the file directly

**Comment by AlexanderGalen** [comment]
I was having this same exact error occur for me, and I'm pretty sure it was a problem with pip, not buster, as I got the same error when trying to install a different package. After some googling I installed pip via homebrew (I had originally done it with easy_install) and after, running `pip install buster` worked just fine.
