### ISSUE TITLE
Buster does not copy assets into static folder

### ISSUE THREAD

**Issue by sebie** [axitkhurana/buster#49]
The issue I am having is: Buster is not copying the relevant asset files from the local server to the static folder -- resulting that the static version has no CSS and JS. Below is how it looks.

[Here is how it looks, after I uploaded it to GitHub.](http://sebie.github.io)[Broken!]

_(Note: I have added the assets to the page just through copying the assets from the folder, but it still does not work)._

---

There are various ways in which you can achieve this, but I used [this](https://ibrahimrahman.github.io/guide-host-a-ghost-blog-on-github-pages-for-free/) guide.  Some alternatives of the guide are listed below; 
1. [Alternative 1 - Mark Daws](http://markdaws.net/blog/fast-free-blog-courtesy-of-ghost-github-and-buster/) 
2. [Alternative 2 - Jack Pearce](http://markdaws.net/blog/fast-free-blog-courtesy-of-ghost-github-and-buster/)
3. [Alternative 3 - Talal Anwar](http://talalanwar.com/host-a-ghost-blog-for-free/)

All of them go through a similar method of achieving the final result.

---

My system:

```
  * Windows 8.1
  * 8 GB RAM
  * Administrative account
  * Using Git Bash (Wget is installed)
  * No errors for in the npm console whilst Buster is brute-forcing the files
```

---

Hope that is enough information to solve it.

Cheers,

**Comment by sebie** [comment]
Not an issue anymore.

**Comment by sebie** [comment]
Not an issue anymore.

**Comment by sebie** [comment]
Sigh, it still is an issue. After multiple people trying to help and reading more how-to's I am going to reopen this. 

I did find a [modified version](https://github.com/leftofnull/buster) of setup.py, but is v1.2.

**Comment by ythecombinator** [comment]
I'm having the same issue here.

**Comment by amphipath** [comment]
try my fork? #67

**Comment by sebie** [comment]
I should have updated y'all on this. After looking around I switched to Jekyll. You can check it out [here](https://sebie.net). Source code is [here](http://github.com/sebie/sebie.net).

Thanks.
