### ISSUE TITLE
Is there a functioning Windows variant / fork of Buster?

### ISSUE THREAD

**Issue by sebie** [axitkhurana/buster#56]
I have found a few variants of Buster for Windows (LeftOfNull), but most of them are outdated. 

So my question is are there any Windows variants or could someone providea guide, on how to use it on Windows?

**Comment by Misiur** [comment]
The Leftofnull version almost works, I'm currently struggling with missing assets though :(

**Comment by Misiur** [comment]
I think I should've forked LON version, but used this one instead. Whoops. https://github.com/Misiur/buster - works on windows 7 for me, all subpages work nicely, and as long your files won't have @ in their names it should work. 

Disclaimer: I have no goddamn idea about python

**Comment by sebie** [comment]
## @Misiur 

**Comment 1.**

I tried LeftOfNull, but had the same struggle as you did. So no luck there.

---

**Comment 2.**

Ok will try your fork of it and will see if it works. I know how python works and all, but I am no python genius.

**Comment by Misiur** [comment]
http://misiur.github.io/ was deployed today with this fork, as long there aren't much differences between  your OS and my Win7, it should work :)

**Comment by sebie** [comment]
Thank you. A few things though:
- The rss page is not formated?
- Could you enable issues in _your_ repo as I don't want to spam notifications here and hijack this.
- I installed it, but adding instruction that LeftOfNull used would not be bad.
- (Trying now).

---

## Update:

Didn't work -- still didn't copy assests. :/

Could you provide steps to how you did it? -`- I might have made a mistake or took a different step then you did.

**Comment by sebie** [comment]
This issue is closed due to @Misiur creating a functional fork of the original Buster. For info go to the refrenced issue above.

**Comment by tomasbjerre** [comment]
You can do it with wget. But I've only tried on Ubuntu. I have Ghost 1.x working with HTTPS and custom domain on Github pages. See https://bjurr.com/ghost-1-0-free-hosting-with-https/
