### ISSUE TITLE
Doesnt Support Static Pages

### ISSUE THREAD

**Issue by raghunayyar** [axitkhurana/buster#7]
Hi @axitkhurana 
I created a static page over Ghost titled say _about me_ but no such directory is generated by buster as a static file. Am I missing something? If no, ! It will be cool to have support for static pages as an enhancement.
Cheers!

**Comment by axitkhurana** [comment]
Hey @raghunayyar,

Buster crawls from the homepage, following links on the site generating pages. So, unless the static page has a link on your blog, it won't be created. I'll think about adding link-less pages manually, but then you'll have to specify the URL to buster.

Easiest way is to add a link to the static page to your blog (E.g. about) and buster will automatically generate it.

**Comment by raghunayyar** [comment]
:+1:

**Comment by montjoile** [comment]
I have the same problem. OK I understand Buster doesn't support static pages, but what about my posts?? Every time I create a post, Buster doesn't generate the static folder containing the post.html file, and I don't know why. Seems only the default Welcome-to-Ghost post is generated
