### ISSUE TITLE
Error install buster on Mac OS El Capitan

### ISSUE THREAD

**Issue by swif2** [axitkhurana/buster#77]
Here is the log after I type "pip install buster":(With everything needed installed). Please kindly help me with this. Thank you very much!

---

Collecting buster
Requirement already satisfied (use --upgrade to upgrade): gitdb==0.5.4 in /usr/local/lib/python2.7/site-packages (from buster)
Requirement already satisfied (use --upgrade to upgrade): smmap==0.8.2 in /usr/local/lib/python2.7/site-packages (from buster)
Requirement already satisfied (use --upgrade to upgrade): GitPython==0.3.2.RC1 in /usr/local/lib/python2.7/site-packages (from buster)
Requirement already satisfied (use --upgrade to upgrade): async==0.6.1 in /usr/local/lib/python2.7/site-packages (from buster)
Collecting pyquery==1.2.8 (from buster)
Requirement already satisfied (use --upgrade to upgrade): docopt==0.6.1 in /usr/local/lib/python2.7/site-packages (from buster)
Collecting lxml>=2.1 (from pyquery==1.2.8->buster)
  Using cached lxml-3.5.0.tar.gz
Collecting cssselect (from pyquery==1.2.8->buster)
Building wheels for collected packages: lxml
  Running setup.py bdist_wheel for lxml
  Complete output from command /usr/local/opt/python/bin/python2.7 -c "import setuptools;**file**='/private/var/folders/cr/d4j4h7v161z300vl8w3w7f4r0000gn/T/pip-build-TzJaWG/lxml/setup.py';exec(compile(open(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" bdist_wheel -d /var/folders/cr/d4j4h7v161z300vl8w3w7f4r0000gn/T/tmpfjizUApip-wheel-:
  Building lxml version 3.5.0.
  Building without Cython.
  Using build configuration of libxslt 1.1.28
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.11-x86_64-2.7
  creating build/lib.macosx-10.11-x86_64-2.7/lxml
  copying src/lxml/**init**.py -> build/lib.macosx-10.11-x86_64-2.7/lxml
  copying src/lxml/_elementpath.py -> build/lib.macosx-10.11-x86_64-2.7/lxml
  copying src/lxml/builder.py -> build/lib.macosx-10.11-x86_64-2.7/lxml
  copying src/lxml/cssselect.py -> build/lib.macosx-10.11-x86_64-2.7/lxml
  copying src/lxml/doctestcompare.py -> build/lib.macosx-10.11-x86_64-2.7/lxml
  copying src/lxml/ElementInclude.py -> build/lib.macosx-10.11-x86_64-2.7/lxml
  copying src/lxml/pyclasslookup.py -> build/lib.macosx-10.11-x86_64-2.7/lxml
  copying src/lxml/sax.py -> build/lib.macosx-10.11-x86_64-2.7/lxml
  copying src/lxml/usedoctest.py -> build/lib.macosx-10.11-x86_64-2.7/lxml
  creating build/lib.macosx-10.11-x86_64-2.7/lxml/includes
  copying src/lxml/includes/__init__.py -> build/lib.macosx-10.11-x86_64-2.7/lxml/includes
  creating build/lib.macosx-10.11-x86_64-2.7/lxml/html
  copying src/lxml/html/**init**.py -> build/lib.macosx-10.11-x86_64-2.7/lxml/html
  copying src/lxml/html/_diffcommand.py -> build/lib.macosx-10.11-x86_64-2.7/lxml/html
  copying src/lxml/html/_html5builder.py -> build/lib.macosx-10.11-x86_64-2.7/lxml/html
  copying src/lxml/html/_setmixin.py -> build/lib.macosx-10.11-x86_64-2.7/lxml/html
  copying src/lxml/html/builder.py -> build/lib.macosx-10.11-x86_64-2.7/lxml/html
  copying src/lxml/html/clean.py -> build/lib.macosx-10.11-x86_64-2.7/lxml/html
  copying src/lxml/html/defs.py -> build/lib.macosx-10.11-x86_64-2.7/lxml/html
  copying src/lxml/html/diff.py -> build/lib.macosx-10.11-x86_64-2.7/lxml/html
  copying src/lxml/html/ElementSoup.py -> build/lib.macosx-10.11-x86_64-2.7/lxml/html
  copying src/lxml/html/formfill.py -> build/lib.macosx-10.11-x86_64-2.7/lxml/html
  copying src/lxml/html/html5parser.py -> build/lib.macosx-10.11-x86_64-2.7/lxml/html
  copying src/lxml/html/soupparser.py -> build/lib.macosx-10.11-x86_64-2.7/lxml/html
  copying src/lxml/html/usedoctest.py -> build/lib.macosx-10.11-x86_64-2.7/lxml/html
  creating build/lib.macosx-10.11-x86_64-2.7/lxml/isoschematron
  copying src/lxml/isoschematron/__init__.py -> build/lib.macosx-10.11-x86_64-2.7/lxml/isoschematron
  copying src/lxml/lxml.etree.h -> build/lib.macosx-10.11-x86_64-2.7/lxml
  copying src/lxml/lxml.etree_api.h -> build/lib.macosx-10.11-x86_64-2.7/lxml
  copying src/lxml/includes/c14n.pxd -> build/lib.macosx-10.11-x86_64-2.7/lxml/includes
  copying src/lxml/includes/config.pxd -> build/lib.macosx-10.11-x86_64-2.7/lxml/includes
  copying src/lxml/includes/dtdvalid.pxd -> build/lib.macosx-10.11-x86_64-2.7/lxml/includes
  copying src/lxml/includes/etreepublic.pxd -> build/lib.macosx-10.11-x86_64-2.7/lxml/includes
  copying src/lxml/includes/htmlparser.pxd -> build/lib.macosx-10.11-x86_64-2.7/lxml/includes
  copying src/lxml/includes/relaxng.pxd -> build/lib.macosx-10.11-x86_64-2.7/lxml/includes
  copying src/lxml/includes/schematron.pxd -> build/lib.macosx-10.11-x86_64-2.7/lxml/includes
  copying src/lxml/includes/tree.pxd -> build/lib.macosx-10.11-x86_64-2.7/lxml/includes
  copying src/lxml/includes/uri.pxd -> build/lib.macosx-10.11-x86_64-2.7/lxml/includes
  copying src/lxml/includes/xinclude.pxd -> build/lib.macosx-10.11-x86_64-2.7/lxml/includes
  copying src/lxml/includes/xmlerror.pxd -> build/lib.macosx-10.11-x86_64-2.7/lxml/includes
  copying src/lxml/includes/xmlparser.pxd -> build/lib.macosx-10.11-x86_64-2.7/lxml/includes
  copying src/lxml/includes/xmlschema.pxd -> build/lib.macosx-10.11-x86_64-2.7/lxml/includes
  copying src/lxml/includes/xpath.pxd -> build/lib.macosx-10.11-x86_64-2.7/lxml/includes
  copying src/lxml/includes/xslt.pxd -> build/lib.macosx-10.11-x86_64-2.7/lxml/includes
  copying src/lxml/includes/etree_defs.h -> build/lib.macosx-10.11-x86_64-2.7/lxml/includes
  copying src/lxml/includes/lxml-version.h -> build/lib.macosx-10.11-x86_64-2.7/lxml/includes
  creating build/lib.macosx-10.11-x86_64-2.7/lxml/isoschematron/resources
  creating build/lib.macosx-10.11-x86_64-2.7/lxml/isoschematron/resources/rng
  copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.macosx-10.11-x86_64-2.7/lxml/isoschematron/resources/rng
  creating build/lib.macosx-10.11-x86_64-2.7/lxml/isoschematron/resources/xsl
  copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.macosx-10.11-x86_64-2.7/lxml/isoschematron/resources/xsl
  copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.macosx-10.11-x86_64-2.7/lxml/isoschematron/resources/xsl
  creating build/lib.macosx-10.11-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.macosx-10.11-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.macosx-10.11-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.macosx-10.11-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.macosx-10.11-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.macosx-10.11-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.macosx-10.11-x86_64-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  running build_ext
  building 'lxml.etree' extension
  creating build/temp.macosx-10.11-x86_64-2.7
  creating build/temp.macosx-10.11-x86_64-2.7/src
  creating build/temp.macosx-10.11-x86_64-2.7/src/lxml
  clang -fno-strict-aliasing -fno-common -dynamic -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/include/libxml2 -Isrc/lxml/includes -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.macosx-10.11-x86_64-2.7/src/lxml/lxml.etree.o -w -flat_namespace
  In file included from src/lxml/lxml.etree.c:323:
  src/lxml/includes/etree_defs.h:14:10: fatal error: 'libxml/xmlversion.h' file not found
  #include "libxml/xmlversion.h"
           ^
  1 error generated.
  Compile failed: command 'clang' failed with exit status 1
  creating var
  creating var/folders
  creating var/folders/cr
  creating var/folders/cr/d4j4h7v161z300vl8w3w7f4r0000gn
  creating var/folders/cr/d4j4h7v161z300vl8w3w7f4r0000gn/T
  cc -I/usr/include/libxml2 -I/usr/include/libxml2 -c /var/folders/cr/d4j4h7v161z300vl8w3w7f4r0000gn/T/xmlXPathInitGZUzN7.c -o var/folders/cr/d4j4h7v161z300vl8w3w7f4r0000gn/T/xmlXPathInitGZUzN7.o
  /var/folders/cr/d4j4h7v161z300vl8w3w7f4r0000gn/T/xmlXPathInitGZUzN7.c:1:10: fatal error: 'libxml/xpath.h' file not found
  #include "libxml/xpath.h"
           ^
  1 error generated.

---

  Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
  Perhaps try: xcode-select --install

---

  error: command 'clang' failed with exit status 1

---

  Failed building wheel for lxml
Failed to build lxml
Installing collected packages: lxml, cssselect, pyquery, buster
  Running setup.py install for lxml
    Complete output from command /usr/local/opt/python/bin/python2.7 -c "import setuptools, tokenize;**file**='/private/var/folders/cr/d4j4h7v161z300vl8w3w7f4r0000gn/T/pip-build-TzJaWG/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /var/folders/cr/d4j4h7v161z300vl8w3w7f4r0000gn/T/pip-KMOkoN-record/install-record.txt --single-version-externally-managed --compile:
    Building lxml version 3.5.0.
    Building without Cython.
    Using build configuration of libxslt 1.1.28
    running install
    running build
    running build_py
    copying src/lxml/includes/lxml-version.h -> build/lib.macosx-10.11-x86_64-2.7/lxml/includes
    running build_ext
    building 'lxml.etree' extension
    clang -fno-strict-aliasing -fno-common -dynamic -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/include/libxml2 -Isrc/lxml/includes -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.macosx-10.11-x86_64-2.7/src/lxml/lxml.etree.o -w -flat_namespace
    In file included from src/lxml/lxml.etree.c:323:
    src/lxml/includes/etree_defs.h:14:10: fatal error: 'libxml/xmlversion.h' file not found
    #include "libxml/xmlversion.h"
             ^
    1 error generated.
    Compile failed: command 'clang' failed with exit status 1
    cc -I/usr/include/libxml2 -I/usr/include/libxml2 -c /var/folders/cr/d4j4h7v161z300vl8w3w7f4r0000gn/T/xmlXPathInitMiJtnU.c -o var/folders/cr/d4j4h7v161z300vl8w3w7f4r0000gn/T/xmlXPathInitMiJtnU.o
    /var/folders/cr/d4j4h7v161z300vl8w3w7f4r0000gn/T/xmlXPathInitMiJtnU.c:1:10: fatal error: 'libxml/xpath.h' file not found
    #include "libxml/xpath.h"
             ^
    1 error generated.
    *********************************************************************************
    Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
    Perhaps try: xcode-select --install
    *********************************************************************************
    error: command 'clang' failed with exit status 1

```
----------------------------------------
```

Command "/usr/local/opt/python/bin/python2.7 -c "import setuptools, tokenize;**file**='/private/var/folders/cr/d4j4h7v161z300vl8w3w7f4r0000gn/T/pip-build-TzJaWG/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /var/folders/cr/d4j4h7v161z300vl8w3w7f4r0000gn/T/pip-KMOkoN-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/cr/d4j4h7v161z300vl8w3w7f4r0000gn/T/pip-build-TzJaWG/lxml

**Comment by dalguji** [comment]
You may try `xcode-select --install` as mentioned in the error message.

**Comment by ghost** [comment]
Thanks @dalguji this resolved a similar issue for me
