### ISSUE TITLE
Buster generate doesn't generate 

### ISSUE THREAD

**Issue by talhaokur** [axitkhurana/buster#78]
Hi!

I've installed buster with pip. And did these:

```
buster setup --gh-repo="http://github.com/seniorokur/seniorokur.github.io.git"
buster generate
buster deploy
```

But nothing happened. I've tried `buster preview` but then I only saw .git folder and README.md file. Where is the problem?

Edit: I also tried `buster generate --domain=http://localhost:2368`

**Comment by Loyalsoldier** [comment]
Try to use this fork: https://github.com/Misiur/buster

**Comment by talhaokur** [comment]
Well, it worked for me. Thank you @Loyalsoldier !
