### ISSUE TITLE
Static pages not working

### ISSUE THREAD

**Issue by NoahVlncrt** [axitkhurana/buster#82]
I have a static page in ghost called about and when I open it. It gives me a github pages error that it can't find the page.

**Comment by albertocoletta** [comment]
Same here.
It seems that buster does not create the page folder.
Looking for a work-around different from doing it manually.

**Comment by NoahVlncrt** [comment]
I was thinking about forking it and trying that but I know absolutely nothing about python. Guess I found my weekend project!
