### ISSUE TITLE
Articles' images get the wrong file extension

### ISSUE THREAD

**Issue by matfire** [axitkhurana/buster#92]
After writing a blog post and trying to generate the website, I found that images are not loaded because their extensions get renamed inside the article's page (another jpeg gets added, so an image name is like image.jpgjpg)
the source code for the article's page is looking something like this
`                <img srcset="../content/images/size/w300/2019/03/plush-design-studio-483666-unsplash-1.jpg 300w,
                           ../content/images/size/w600/2019/03/plush-design-studio-483666-unsplash-1.jpgg 600w,
                          ../content/images/size/w1000/2019/03/plush-design-studio-483666-unsplash-1.jpgpg 1000w,
                         ../content/images/size/w2000/2019/03/plush-design-studio-483666-unsplash-1.jpgjpg 2000w" sizes="(max-width: 800px) 400px,
                            (max-width: 1170px) 700px,
                            1400px" src="../content/images/size/w2000/2019/03/plush-design-studio-483666-unsplash-1.jpg" alt="Deploying Ghost on Github">`

The "amp" page has the good extension

**Comment by axitkhurana** [comment]
Hi @matfire, buster isn't maintained anymore. Sorry for the trouble!

Checkout publishing static sites with Ghost and Gatsby:

https://www.gatsbyjs.org/blog/2019-01-14-modern-publications-with-gatsby-ghost/
https://docs.ghost.org/api/gatsby/

It's still early days for that project but looks like it's the right way to go.

**Comment by matfire** [comment]
Hey @axitkhurana, thanks for the reply! Sorry to have bothered you with the issue, I hadn't noticed the project wasn't being maintained. Thanks for the links, I'll check them out!
